### ISSUE TITLE
SqlServerIncrementRecordApplier没有在代码中使用吗？

### ISSUE THREAD

**Issue by checkme5** [alswl/yugong#1]

**Comment by alswl** [comment]
是的，使用 IncrementRecordApplier。

**Comment by checkme5** [comment]
多谢，请问yugong.yaml怎么搭配使用，能再写一篇wiki吗？

**Comment by alswl** [comment]
参考 `src/it/resources/sample_config/`，目前没有精力。

**Comment by checkme5** [comment]
> 参考 `src/it/resources/sample_config/`，目前没有精力。

ok，了解了。
