### ISSUE TITLE
多键 或 键不是数字 这个与单键同步有什么区别么 ？

### ISSUE THREAD

**Issue by xinzhuxiansheng** [alswl/yugong#4]
/**
   * is only one primary key, and this key is number
   */
  private boolean isOnlyPkIsNumber(Table table) {
    if (table.getPrimaryKeys() != null && table.getPrimaryKeys().size() == 1) {
      return YuGongUtils.isNumber(table.getPrimaryKeys().get(0).getType());
    }

    return false;
  }

没有太明白 ，同步表的时候，为什么只支持到 单主键，或者键必须是数值 。这样有什么区别么？

**Comment by alswl** [comment]
建议去上游仓库提这个问题。

我个人观点是，迁移目标表表需要遵循设计范式「单表有唯一主键列，并且是数字（或者十六进制 guid）」。具体原因可以看阿里开发规约。
