### ISSUE TITLE
有没有删字段或者加字段的配置方式？

### ISSUE THREAD

**Issue by hlguo** [alswl/yugong#6]
有没有加字段删字段的配置方式？

**Comment by alswl** [comment]
有的，代码见：

https://github.com/alswl/yugong/blob/feature/sql-server-to-mysql-overview/src/main/java/com/taobao/yugong/translator/ColumnFixDataTranslator.java#L45

参考 https://github.com/alswl/yugong/blob/feature/sql-server-to-mysql-overview/src/it/resources/sample_config/1_mysql-mssql-full-trans.yaml#L75 YAML 添加 `new_columns` 字段
