### ISSUE TITLE
两个配置文件的样例能提供下嘛?链接打不开了!

### ISSUE THREAD

**Issue by qiankun1024** [alswl/yugong#9]
现在在配置SQLserver到MySQL的数据同步，使用的sync-mssql-mysql.properties和mssql-mysql.yaml是从官方的yugong.properties.sample和yugong.yaml.sample修改而来，其中 yugong.database.source.type=SQLSERVER直接报错了:
java.lang.IllegalArgumentException: No enum constant com.taobao.yugong.common.model.DbType.SQLSERVE

**Comment by alswl** [comment]
配置参考 https://github.com/alswl/yugong/issues/3

你使用的 jar 包是上游的包，不是本项目的。
